name: OmniTab
version: '${project.version}'
main: com.omnitab.core.OmniTab
api-version: 1.13
authors: [Samra]
description: Universal Cross-Version TAB Plugin
website: https://github.com/samra/OmniTab
